version: '3'
services:
  laravel:
    build:
      context: ./
    environment:
    - DB_CONNECTION=mysql
    - DB_HOST=laravel-backend-mysql-1
    - DB_PORT=3306
    - DB_DATABASE=backend
    - DB_USERNAME=root
    - DB_PASSWORD=root_password
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_DATABASE: backend
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Mount your SQL dump folder
    networks:
      - app-network

networks:
  app-network:
